[package]
name        = "flix"
description = "Flix apps and feature tests."
version     = "0.1.0"
flix        = "0.66.2"
license     = "Apache-2.0"
authors     = ["Objektwerks <objektwerks@runbox.com>"]
